export const states = ["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"];

export type TemplateClause = { id: string; title: string; text: string };
export type DocumentTemplate = {
  id: string;
  name: string;
  icon: string;
  description: string;
  body: string;
  footer: string;
  clauses: TemplateClause[];
};

const agreementFooter = `BREEDER / SELLER\nPrinted name: [BREEDER NAME]\nSignature: ______________________________  Date: ______________\n\nBUYER\nPrinted name: [BUYER NAME]\nSignature: ______________________________  Date: ______________\n\nAdditional buyer (if applicable)\nPrinted name: [ADDITIONAL BUYER NAME]\nSignature: ______________________________  Date: ______________`;

export const templates: DocumentTemplate[] = [
  {
    id: "sales", name: "Puppy Sales Agreement", icon: "§",
    description: "Detailed sale, payment, transfer, care, registration, return, default, and signature terms.",
    body: `PUPPY SALES AGREEMENT\n\nThis Puppy Sales Agreement (\"Agreement\") is entered into on [AGREEMENT DATE] by and between the breeder/seller and buyer identified below. The parties agree that the puppy described in this Agreement will be transferred subject to every selected term and addendum.\n\nBREEDER / SELLER\nLegal name: [BREEDER LEGAL NAME]\nKennel name: [KENNEL NAME]\nAddress: [BREEDER ADDRESS]\nPhone: [BREEDER PHONE]\nEmail: [BREEDER EMAIL]\n\nBUYER\nLegal name: [BUYER LEGAL NAME]\nAddress: [BUYER ADDRESS]\nPhone: [BUYER PHONE]\nEmail: [BUYER EMAIL]\n\nPUPPY IDENTIFICATION\nRegistered name: [REGISTERED NAME]\nCall name: [PUPPY NAME]\nBreed: [BREED]\nSex: [SEX]\nDate of birth: [DATE OF BIRTH]\nColor / markings: [COLOR AND MARKINGS]\nCoat type: [COAT TYPE]\nMicrochip number: [MICROCHIP NUMBER]\nRegistry / registration number: [REGISTRY AND NUMBER]\nSire: [SIRE]\nDam: [DAM]\n\nFINANCIAL TERMS\nPurchase price: [PURCHASE PRICE]\nDeposit received: [DEPOSIT AMOUNT]\nSales tax / fees: [TAX OR FEES]\nBalance due: [BALANCE DUE]\nBalance due date: [DUE DATE]\nPayment method: [PAYMENT METHOD]\nTransfer / delivery date: [TRANSFER DATE]\nTransfer location or method: [TRANSFER DETAILS]`,
    footer: agreementFooter,
    clauses: [
      {id:"sale-payment",title:"Purchase price and payment",text:"Buyer agrees to pay the purchase price and all stated fees according to the schedule above. Ownership will not transfer, and registration papers may be withheld, until cleared funds are received. A returned, reversed, disputed, or dishonored payment does not satisfy Buyer’s obligation."},
      {id:"sale-transfer",title:"Transfer and acceptance",text:"Buyer accepts the puppy on the transfer date after having an opportunity to review the puppy, veterinary records, identification, and terms of this Agreement. Risk of ordinary care, supervision, travel, and accidental loss transfers to Buyer when the puppy is physically delivered to Buyer or Buyer’s authorized transporter."},
      {id:"sale-records",title:"Records provided",text:"Breeder will provide the records selected for this placement, which may include vaccination and deworming history, microchip information, feeding instructions, registration documents, pedigree, and health records. Buyer will preserve these records and provide them to the puppy’s veterinarian."},
      {id:"sale-exam",title:"Initial veterinary examination",text:"Buyer will arrange an examination by a licensed veterinarian within [EXAM PERIOD] after transfer and will provide Breeder a complete written report within [NOTICE PERIOD] if the veterinarian identifies a serious concern. Routine findings, parasites commonly addressed by standard treatment, stress-related symptoms, or conditions disclosed before transfer are handled under the selected Health Guarantee rather than as an automatic cancellation of this sale."},
      {id:"sale-care",title:"Buyer standards of care",text:"Buyer will provide safe housing, appropriate nutrition, clean water, routine and emergency veterinary care, parasite prevention, exercise, training, socialization, grooming, and humane treatment. Buyer will not leave the dog in unsafe temperatures, allow uncontrolled roaming, or use the dog for unlawful fighting, research, resale brokering, or neglectful breeding."},
      {id:"sale-safety",title:"Small-breed and puppy safety",text:"Buyer acknowledges that young and small-breed puppies may require frequent meals, careful supervision, protection from falls and larger animals, and prompt attention to lethargy, weakness, vomiting, diarrhea, refusal to eat, breathing difficulty, or other concerning symptoms. Buyer agrees to follow the written feeding and transition instructions supplied at transfer."},
      {id:"sale-registration",title:"Registration and breeding status",text:"The puppy is transferred with [REGISTRATION STATUS] registration. Limited registration, pet-only placement, co-ownership, breeding rights, name restrictions, and paper-release conditions stated in this Agreement or an attached addendum are material terms. Buyer may not represent that broader rights were included unless they appear in writing."},
      {id:"sale-return",title:"Return-to-breeder requirement",text:"If Buyer can no longer keep the dog, Buyer will contact Breeder before surrendering, selling, gifting, leasing, or transferring the dog. The parties will discuss return or an approved placement. Unless separately stated in writing, a return does not guarantee a refund and does not erase unpaid obligations."},
      {id:"sale-no-resale",title:"Prohibited transfers",text:"Buyer will not transfer the dog to a pet store, broker, auction, laboratory, rescue, shelter, commercial wholesaler, or person prohibited from animal ownership. Any approved new owner must receive the dog’s records and agree to applicable continuing restrictions."},
      {id:"sale-default",title:"Material breach and enforcement",text:"Unauthorized breeding, prohibited transfer, intentional misrepresentation, cruelty, neglect, or failure to pay is a material breach. Breeder may pursue available contractual remedies, recovery of the dog when permitted, documented enforcement costs, and any specific remedy stated in a selected addendum."},
      {id:"sale-governing",title:"Governing law and venue",text:"This Agreement is governed by the laws of {{STATE}}, without regard to conflict-of-law rules. Any mandatory consumer or animal-sale protection that cannot be waived remains applicable. The parties agree to the venue stated here unless applicable law requires another forum: [COUNTY AND STATE]."},
      {id:"sale-entire",title:"Entire agreement; electronic copies",text:"This Agreement and its incorporated addenda are the complete agreement concerning this puppy and replace prior oral statements or messages. A change must be written and accepted by both parties. Electronic signatures and counterparts may be treated as originals. If one provision is unenforceable, the remaining provisions continue to the extent permitted."}
    ]
  },
  {
    id:"health", name:"Health Guarantee", icon:"+",
    description:"Exam procedures, notice requirements, covered conditions, exclusions, evidence, and available remedies.",
    body:`HEALTH GUARANTEE\n\nThis Health Guarantee applies to the puppy identified below and is incorporated into the parties’ Puppy Sales Agreement.\n\nPuppy: [PUPPY NAME]\nBreed: [BREED]\nSex: [SEX]\nDate of birth: [DATE OF BIRTH]\nMicrochip: [MICROCHIP NUMBER]\nTransfer date: [TRANSFER DATE]\nBuyer: [BUYER NAME]\nBreeder: [BREEDER NAME]\nPurchase price: [PURCHASE PRICE]\nInitial exam deadline: [EXAM DEADLINE]\nGuarantee period: [GUARANTEE PERIOD]`,
    footer:agreementFooter,
    clauses:[
      {id:"health-baseline",title:"Condition at transfer",text:"Breeder states that, to Breeder’s knowledge and based on the records supplied, the puppy is suitable for transfer on the stated date except for conditions specifically disclosed here: [DISCLOSED CONDITIONS]. No promise is made regarding traits or conditions not expressly covered below."},
      {id:"health-exam",title:"Required initial examination",text:"Buyer must have the puppy examined by a licensed veterinarian who is independent of Breeder within [EXAM PERIOD] after transfer. Failure to complete the examination within that period may end coverage for conditions that a timely examination reasonably could have identified, except where {{STATE}} law requires otherwise."},
      {id:"health-notice",title:"Notice and documentation",text:"Buyer must notify Breeder in writing within [NOTICE PERIOD] after a concerning diagnosis and before authorizing non-emergency euthanasia or major treatment when consultation is reasonably possible. Notice must include the veterinarian’s signed report, examination findings, diagnostic results, treatment recommendation, prognosis, and the puppy’s microchip or other identifying information."},
      {id:"health-covered",title:"Covered conditions",text:"Coverage applies only to the following conditions when first diagnosed within the stated guarantee period and supported by appropriate testing: [LIST COVERED CONGENITAL / HEREDITARY CONDITIONS]. A veterinarian’s suspicion without supporting findings is not a final diagnosis, but emergency stabilization should never be delayed."},
      {id:"health-remedy",title:"Available remedy",text:"For a verified covered condition, the selected remedy is: [REPLACEMENT / REFUND / VETERINARY COST CONTRIBUTION / OTHER]. The maximum monetary remedy will not exceed [REMEDY LIMIT]. Buyer must satisfy the documentation and return requirements applicable to the selected remedy, subject to rights that cannot be limited under {{STATE}} law."},
      {id:"health-return",title:"Return when required for remedy",text:"If Buyer chooses or accepts a remedy requiring return, the puppy must be returned with registration materials and records at [RETURN LOCATION] within [RETURN PERIOD], unless the puppy is medically unable to travel or applicable law provides otherwise. Breeder will not require transport that the attending veterinarian considers unsafe."},
      {id:"health-exclusions",title:"General exclusions",text:"Unless expressly added, coverage does not include injury, poisoning, ingestion, accident, neglect, abuse, improper diet, dehydration, hypoglycemia caused or worsened by missed feeding, failure to obtain treatment, parasites, coccidia, giardia, kennel cough, stress-related diarrhea, retained deciduous teeth, hernia disclosed at transfer, cosmetic traits, adult size, temperament changes, fertility, or conditions caused after transfer."},
      {id:"health-treatment",title:"Buyer’s duty to mitigate",text:"Buyer will follow reasonable veterinary instructions and will not delay necessary care while waiting for Breeder’s response. Breeder is not responsible for an avoidable worsening caused by Buyer’s failure to seek timely treatment, administer prescribed care, provide records, or follow feeding and transition instructions."},
      {id:"health-necropsy",title:"Death of puppy",text:"If the puppy dies during the guarantee period and Buyer seeks a remedy, Buyer must notify Breeder promptly and, when reasonably available, obtain a necropsy from a licensed veterinarian or veterinary diagnostic laboratory. The report must identify the probable cause of death. Breeder may request review by another veterinarian at Breeder’s expense."},
      {id:"health-costs",title:"Veterinary expenses",text:"Routine and emergency veterinary expenses are Buyer’s responsibility unless the selected remedy expressly states otherwise. Buyer may not deduct veterinary charges from an unpaid purchase balance without Breeder’s written agreement."},
      {id:"health-state",title:"State protections",text:"This guarantee will be administered consistently with mandatory {{STATE}} animal-sale and consumer-protection requirements. Any statutory notice, remedy, examination period, or documentation right that cannot lawfully be waived controls over a conflicting provision."}
    ]
  },
  {
    id:"deposit", name:"Deposit Agreement", icon:"$",
    description:"Reservation, selection, payment deadlines, breeder and buyer cancellation, transfer, and refund terms.",
    body:`PUPPY DEPOSIT AND RESERVATION AGREEMENT\n\nBreeder: [BREEDER NAME]\nBuyer / Depositor: [BUYER NAME]\nPuppy or litter reserved: [PUPPY / LITTER DESCRIPTION]\nBreed: [BREED]\nExpected or actual birth date: [DATE]\nSelection position: [PICK POSITION]\nAnticipated go-home period: [GO-HOME WINDOW]\nTotal purchase price: [PURCHASE PRICE]\nDeposit amount: [DEPOSIT AMOUNT]\nDeposit date: [DEPOSIT DATE]\nRemaining balance: [BALANCE]\nBalance deadline: [BALANCE DUE DATE]`,
    footer:agreementFooter,
    clauses:[
      {id:"deposit-purpose",title:"Purpose of deposit",text:"The deposit reserves the identified puppy, litter position, or future selection opportunity according to this Agreement. It is not a transfer of ownership and does not permit Buyer to take possession before Breeder confirms readiness and all required funds have cleared."},
      {id:"deposit-application",title:"Application to purchase price",text:"If the placement is completed, the cleared deposit will be credited toward the total purchase price. Buyer remains responsible for the stated balance, taxes, transportation, optional services, and other agreed charges."},
      {id:"deposit-buyer-cancel",title:"Buyer cancellation",text:"If Buyer withdraws, becomes unavailable, fails to complete required screening, rejects an available puppy that meets the written reservation criteria, or misses a payment or selection deadline, the deposit will be handled as follows: [NONREFUNDABLE / PARTIALLY REFUNDABLE / TRANSFERABLE TERMS]."},
      {id:"deposit-breeder-cancel",title:"Breeder unable or unwilling to place",text:"If Breeder decides the placement should not proceed, cannot provide a puppy meeting the written reservation criteria within [TIME PERIOD], or the reserved puppy becomes unavailable before transfer, Buyer may choose the stated remedy: [REFUND / TRANSFER TO FUTURE LITTER / ALTERNATE PUPPY], unless another remedy is required by {{STATE}} law."},
      {id:"deposit-selection",title:"Selection process",text:"Selections will occur in the order and manner stated here: [SELECTION PROCESS]. Buyer must respond within [RESPONSE WINDOW] after notice. Color, coat, sex, estimated adult size, temperament, and show or breeding potential are not guaranteed unless expressly written as reservation criteria."},
      {id:"deposit-transfer",title:"Transfer to another litter or puppy",text:"A deposit may be transferred only under these conditions: [TRANSFER CONDITIONS]. Any transfer is limited to [NUMBER] occurrence(s) and must be used by [EXPIRATION DATE]. Price differences and updated terms may apply to a later litter."},
      {id:"deposit-balance",title:"Balance and missed deadlines",text:"The remaining balance is due by the stated deadline in cleared funds. If Buyer misses the deadline without a written extension, Breeder may release the reservation and apply the deposit according to the Buyer-cancellation provision."},
      {id:"deposit-communication",title:"Communication and contact changes",text:"Buyer will keep current email, telephone, and address information on file and will monitor communications during selection and transfer periods. Notice sent to Buyer’s last provided email or telephone contact is sufficient for contractual deadlines unless the parties agree otherwise."},
      {id:"deposit-no-ownership",title:"No ownership before transfer",text:"Buyer has no ownership, possession, breeding, registration, or decision-making rights in a puppy before the final agreement is signed, payment clears, and physical transfer occurs."},
      {id:"deposit-state",title:"Governing terms",text:"This Agreement is governed by {{STATE}} law. Any mandatory deposit, consumer, or animal-sale rule that cannot be waived remains effective. Written changes must be accepted by both parties."}
    ]
  },
  {
    id:"bill", name:"Bill of Sale", icon:"✓",
    description:"Complete payment receipt and ownership-transfer record with identification, disclosures, and included property.",
    body:`DOG / PUPPY BILL OF SALE\n\nDate of sale: [SALE DATE]\nTransfer date and time: [TRANSFER DATE AND TIME]\nTransfer location: [TRANSFER LOCATION]\n\nSELLER\nName: [SELLER NAME]\nAddress: [SELLER ADDRESS]\nPhone / email: [SELLER CONTACT]\n\nBUYER\nName: [BUYER NAME]\nAddress: [BUYER ADDRESS]\nPhone / email: [BUYER CONTACT]\n\nDOG / PUPPY\nRegistered name: [REGISTERED NAME]\nCall name: [CALL NAME]\nBreed: [BREED]\nSex: [SEX]\nDate of birth: [DATE OF BIRTH]\nColor / markings: [COLOR / MARKINGS]\nMicrochip: [MICROCHIP]\nRegistry and number: [REGISTRATION]\nSire / Dam: [SIRE] / [DAM]\n\nPAYMENT RECORD\nTotal sale price: [TOTAL]\nDeposit previously paid: [DEPOSIT]\nFinal payment received: [FINAL PAYMENT]\nTaxes / other charges: [CHARGES]\nTotal received: [TOTAL RECEIVED]\nPayment method / reference: [PAYMENT REFERENCE]`,
    footer:agreementFooter,
    clauses:[
      {id:"bill-receipt",title:"Receipt and consideration",text:"Seller acknowledges receipt of the amount stated above, subject to final settlement of any electronic, card, or check payment. Buyer acknowledges receipt of the identified dog and the property and records listed in this Bill of Sale."},
      {id:"bill-transfer",title:"Transfer of ownership",text:"Seller transfers Seller’s ownership interest to Buyer on the stated transfer date, subject to any written co-ownership, security interest, registration limitation, payment plan, breeding restriction, return requirement, or addendum incorporated here: [INCORPORATED AGREEMENTS]."},
      {id:"bill-items",title:"Items and records delivered",text:"The following accompanied the dog: [REGISTRATION PAPERS / HEALTH RECORD / MICROCHIP RECORD / PEDIGREE / FOOD / SUPPLIES / OTHER]. Buyer will confirm any missing item here: [MISSING OR PENDING ITEMS]."},
      {id:"bill-disclosures",title:"Seller disclosures",text:"Seller disclosed the following known conditions, traits, treatments, or pending matters before sale: [DISCLOSURES OR NONE]. Buyer acknowledges receiving an opportunity to ask questions and review the available records."},
      {id:"bill-registration",title:"Registration documents",text:"Registration status is [STATUS]. If papers are pending, conditioned on alteration, co-owned, or held until payment completion, the release requirement and expected timing are: [PAPER RELEASE TERMS]."},
      {id:"bill-no-extra",title:"No unstated promises",text:"This Bill of Sale records payment and transfer. Any health guarantee, breeding right, return obligation, or continuing restriction applies only if included here or in an incorporated written agreement signed or accepted by the parties."},
      {id:"bill-state",title:"Governing law",text:"This transfer is governed by {{STATE}} law. Mandatory rights and disclosures that cannot be waived remain applicable."}
    ]
  },
  {
    id:"spay", name:"Spay / Neuter Agreement", icon:"◇",
    description:"Alteration deadline, veterinarian documentation, health extensions, registration limits, and noncompliance terms.",
    body:`SPAY / NEUTER AND PET-PLACEMENT AGREEMENT\n\nBreeder: [BREEDER NAME]\nBuyer: [BUYER NAME]\nDog: [DOG NAME]\nBreed / sex: [BREED / SEX]\nDate of birth: [DATE OF BIRTH]\nMicrochip: [MICROCHIP]\nRegistration status: [REGISTRATION STATUS]\nRequired alteration age or date: [DEADLINE]\nProof due to Breeder: [PROOF DEADLINE]`,
    footer:agreementFooter,
    clauses:[
      {id:"spay-purpose",title:"Pet-only placement",text:"The dog is placed as a companion and not with breeding rights. Buyer will not intentionally or accidentally breed, collect or sell semen, transfer embryos, advertise stud service, or represent offspring as authorized by Breeder."},
      {id:"spay-deadline",title:"Alteration requirement",text:"Buyer will have the dog spayed or neutered by a licensed veterinarian no later than [ALTERATION DEADLINE], provided the veterinarian considers the procedure medically appropriate at that time."},
      {id:"spay-proof",title:"Proof of completion",text:"Buyer will provide a legible veterinary certificate or paid invoice identifying the dog, microchip when available, procedure, veterinarian, and completion date within [PROOF PERIOD] after surgery."},
      {id:"spay-extension",title:"Medical extension",text:"If the veterinarian recommends delay, Buyer must provide a signed statement before the deadline explaining the medical reason and proposed new date. A reasonable written extension will not be unreasonably withheld when supported by veterinary guidance."},
      {id:"spay-registration",title:"Registration limitation",text:"Registration will remain [LIMITED / WITHHELD / CO-OWNED] according to these terms: [REGISTRATION TERMS]. Completion of alteration does not automatically expand registration or show rights unless separately stated."},
      {id:"spay-accidental",title:"Accidental breeding",text:"Buyer must immediately notify Breeder of any suspected mating or pregnancy and obtain veterinary guidance. An accidental breeding does not erase Buyer’s obligations. The parties will apply the agreed remedy and prioritize the health of the dog."},
      {id:"spay-remedy",title:"Noncompliance",text:"Failure to complete alteration or provide an approved extension is a material breach. The agreed contractual remedy is [REMEDY / LIQUIDATED DAMAGES], to the extent enforceable under {{STATE}} law, in addition to any restriction on registration or transfer stated in the Sales Agreement."},
      {id:"spay-transfer",title:"Continuing restriction",text:"Buyer may not transfer the dog intact without Breeder’s prior written approval. Any approved transferee must accept the remaining alteration and proof obligations in writing."}
    ]
  },
  {
    id:"breeding", name:"Breeding Rights Addendum", icon:"◎",
    description:"Specific breeding authorization, testing, age, frequency, registration, placement, reporting, and breach terms.",
    body:`BREEDING RIGHTS ADDENDUM\n\nThis Addendum modifies the Puppy Sales Agreement dated [SALES AGREEMENT DATE]. Breeding permission is limited to the dog and buyer identified below and is not a general license to breed or transfer breeding rights.\n\nBreeder / Seller: [BREEDER NAME]\nBuyer: [BUYER NAME]\nDog registered name: [REGISTERED NAME]\nCall name: [CALL NAME]\nBreed / sex: [BREED / SEX]\nDate of birth: [DATE OF BIRTH]\nMicrochip: [MICROCHIP]\nRegistry / number: [REGISTRATION]\nBreeding-rights fee included: [AMOUNT]\nCo-ownership status: [CO-OWNERSHIP TERMS]\nAuthorized registry / registries: [REGISTRIES]`,
    footer:agreementFooter,
    clauses:[
      {id:"breed-grant",title:"Limited grant of breeding rights",text:"Breeder grants Buyer a personal, nontransferable right to breed the identified dog only under this Addendum. No right is granted for another dog, transferee, broker, kennel, or co-owner unless Breeder approves it in writing."},
      {id:"breed-health",title:"Health testing before breeding",text:"Before the first breeding, Buyer must complete and document the following age-appropriate examinations or tests: [DNA PANEL], [CARDIAC], [PATELLA], [EYE], [HIPS], and [OTHER BREED-SPECIFIC TESTS]. Results must meet these minimum criteria: [REQUIRED RESULTS]. Buyer will provide copies before mating."},
      {id:"breed-age",title:"Minimum and maximum breeding age",text:"The dog may not be bred before [MINIMUM AGE / HEALTH MILESTONE] or after [MAXIMUM AGE], and never when a veterinarian advises that breeding would create an unreasonable health risk."},
      {id:"breed-frequency",title:"Breeding frequency and recovery",text:"A female may have no more than [NUMBER] litters during [PERIOD] and must receive appropriate recovery between litters. A male may be used subject to veterinary health, infectious-disease screening, and the limits stated here: [MALE USE LIMITS]."},
      {id:"breed-mate",title:"Approval and standards for mate",text:"Any proposed mate must be the same recognized breed, appropriately registered, temperamentally suitable, and tested for the conditions listed here: [MATE REQUIREMENTS]. Written approval [IS / IS NOT] required before each mating. Buyer will avoid pairings that create prohibited color, coat, merle, size, or known genetic risk combinations identified here: [PAIRING RESTRICTIONS]."},
      {id:"breed-vet",title:"Veterinary and reproductive care",text:"Buyer will provide pre-breeding evaluation, pregnancy care, safe whelping preparation, emergency access, postpartum care, and neonatal support appropriate to the breed. Buyer is responsible for reproductive, delivery, cesarean, puppy, and emergency expenses unless another written agreement applies."},
      {id:"breed-records",title:"Breeding and litter records",text:"Buyer will maintain dates of mating, identity and registration of the mate, health-test results, pregnancy records, whelping details, puppy identification, weights, health care, placements, and registration. Buyer will provide Breeder a litter report within [REPORTING PERIOD]."},
      {id:"breed-placement",title:"Placement of offspring",text:"Buyer will screen homes, use written placement agreements, disclose known health information, provide records, and accept responsibility for puppies produced. Offspring may not be sold through auctions, brokers, pet stores, wholesalers, laboratories, or undisclosed third-party resale channels."},
      {id:"breed-registration",title:"Registration of offspring",text:"Litters and offspring may be registered only with [AUTHORIZED REGISTRIES] and under the kennel-name, co-breeder, prefix, or naming requirements stated here: [REGISTRATION AND NAMING TERMS]. Buyer will not issue full registration contrary to an offspring’s written placement restrictions."},
      {id:"breed-transfer",title:"No transfer of intact dog or rights",text:"Buyer may not sell, lease, co-own, gift, or otherwise transfer the intact dog or any breeding interest without Breeder’s prior written approval. Any approved transfer must preserve applicable health, registration, reporting, and return obligations."},
      {id:"breed-stop",title:"Suspension of breeding",text:"Buyer will stop breeding the dog if a serious heritable condition, unsafe reproductive complication, disqualifying temperament issue, or veterinary contraindication is identified. The parties will document whether alteration, retirement, additional testing, or restricted pairing is required."},
      {id:"breed-breach",title:"Unauthorized breeding and remedy",text:"Breeding without required testing or approval, prohibited transfer, falsification of records, or registration contrary to this Addendum is a material breach. The agreed remedy is [LIQUIDATED DAMAGES / RETURN / REGISTRATION ACTION / OTHER], to the extent enforceable under {{STATE}} law, together with documented enforcement expenses when recoverable."},
      {id:"breed-state",title:"Governing terms",text:"This Addendum is governed by {{STATE}} law and controls over inconsistent breeding-rights language in the Sales Agreement. All other Sales Agreement terms remain effective."}
    ]
  },
  {
    id:"guardian", name:"Guardian Home Agreement", icon:"⌂",
    description:"Possession, ownership, care standards, access, breeding events, expenses, relocation, retirement, and transfer.",
    body:`GUARDIAN HOME AGREEMENT\n\nBreeder / legal owner: [BREEDER NAME]\nGuardian: [GUARDIAN NAME]\nDog: [REGISTERED NAME / CALL NAME]\nBreed / sex: [BREED / SEX]\nDate of birth: [DATE OF BIRTH]\nMicrochip / registration: [IDENTIFIERS]\nGuardian address: [ADDRESS]\nStart date: [DATE]\nAnticipated retirement milestone: [RETIREMENT TERMS]`,
    footer:agreementFooter,
    clauses:[
      {id:"guardian-ownership",title:"Ownership and possession",text:"Breeder retains legal ownership and breeding decision authority until the retirement and transfer conditions are completed. Guardian receives day-to-day possession and must not sell, lease, breed, surrender, or encumber the dog."},
      {id:"guardian-care",title:"Daily care",text:"Guardian will provide indoor family housing, appropriate nutrition, exercise, training, grooming, socialization, parasite prevention, routine veterinary care, identification, supervision, and humane treatment consistent with the written care plan."},
      {id:"guardian-vet",title:"Veterinary decisions and expenses",text:"Guardian is responsible for [ROUTINE EXPENSES]. Breeder is responsible for [BREEDING-RELATED EXPENSES]. Emergency care must not be delayed; Guardian will notify Breeder as soon as reasonably possible and obtain itemized records."},
      {id:"guardian-access",title:"Breeder access",text:"Guardian will make the dog available on reasonable notice for health testing, breeding evaluation, mating, reproductive care, whelping, shows, registration needs, and related appointments. Pickup, return, notice, and expected duration will follow: [ACCESS TERMS]."},
      {id:"guardian-repro",title:"Heat cycles and reproductive events",text:"Guardian will promptly report heat-cycle signs, prevent unauthorized mating, and follow written separation instructions. During approved breeding, pregnancy, whelping, or litter care, the dog may reside with Breeder for the period reasonably required."},
      {id:"guardian-location",title:"Relocation and travel",text:"Guardian will not permanently relocate the dog, move beyond [DISTANCE], board for an extended period, or take the dog outside [TRAVEL AREA] without prior written notice or approval as specified here: [LOCATION TERMS]."},
      {id:"guardian-loss",title:"Loss, theft, injury, or death",text:"Guardian must notify Breeder immediately of escape, theft, serious injury, hospitalization, or death, cooperate with recovery efforts, and preserve veterinary or official records. Guardian is responsible for loss caused by intentional misconduct or grossly unsafe care to the extent provided by {{STATE}} law."},
      {id:"guardian-end",title:"Early termination",text:"If Guardian cannot continue or materially breaches this Agreement, the dog must be returned to Breeder at [LOCATION] with records and property. The parties will follow the transition procedure stated here: [TERMINATION PROCEDURE]."},
      {id:"guardian-retire",title:"Retirement and ownership transfer",text:"After [NUMBER / AGE / MILESTONE] and completion of required retirement care or alteration, Breeder will transfer ownership to Guardian under these conditions: [TRANSFER CONDITIONS]. Registration and records will be released according to the stated timeline."}
    ]
  },
  {
    id:"stud", name:"Stud Service Agreement", icon:"∞",
    description:"Breeding method, timing, fees, testing, repeat service, litter definition, expenses, and ownership terms.",
    body:`STUD SERVICE AGREEMENT\n\nStud owner: [STUD OWNER]\nDam owner: [DAM OWNER]\nStud: [STUD REGISTERED NAME / NUMBER]\nDam: [DAM REGISTERED NAME / NUMBER]\nBreed: [BREED]\nPlanned breeding method: [NATURAL / FRESH / CHILLED / FROZEN]\nPlanned breeding dates: [DATES]\nStud fee: [FEE]\nDeposit / booking fee: [DEPOSIT]\nBalance deadline: [DUE DATE]\nVeterinarian / reproduction provider: [PROVIDER]`,
    footer:agreementFooter,
    clauses:[
      {id:"stud-eligibility",title:"Eligibility and documentation",text:"Each owner confirms authority to breed the identified dog and will provide registration, pedigree, identification, and current health-testing records requested before service. Required testing includes: [TESTING REQUIREMENTS]."},
      {id:"stud-infection",title:"Infectious-disease screening",text:"The dam must satisfy the following screening and timing requirements: [BRUCELLOSIS / VAGINAL CULTURE / OTHER]. The stud owner may refuse service when documentation is missing, expired, or indicates an unreasonable health risk."},
      {id:"stud-timing",title:"Timing and breeding method",text:"The dam owner is responsible for progesterone or other timing unless stated otherwise. Collection, shipment, insemination, boarding, handling, and veterinary arrangements will follow: [PROCEDURE]. Neither party guarantees conception from a particular date or method."},
      {id:"stud-fees",title:"Fees and expenses",text:"The stud fee is earned according to [AT BOOKING / FIRST SERVICE / CONFIRMED PREGNANCY / LIVE LITTER]. The dam owner is responsible for [COLLECTION / SHIPPING / VETERINARY / BOARDING / TRAVEL] expenses, including repeat-service expenses unless expressly included."},
      {id:"stud-litter",title:"Definition of qualifying litter",text:"For this Agreement, a qualifying litter means [NUMBER] live puppy or puppies surviving [PERIOD], unless the parties state another definition here: [DEFINITION]. Veterinary or registration records may be requested to verify outcome."},
      {id:"stud-repeat",title:"Repeat-service terms",text:"If no qualifying litter results, the dam owner may receive [ONE REPEAT SERVICE / OTHER REMEDY] for the same dam or an approved substitute within [TIME LIMIT], provided notice and veterinary evidence are supplied within [NOTICE PERIOD]. Cash refunds are [AVAILABLE / NOT AVAILABLE] as stated here: [REFUND TERMS]."},
      {id:"stud-substitute",title:"Substitute stud or dam",text:"No substitute dog may be used without both owners’ written agreement. A change may affect fee, testing, timing, shipping, and repeat-service eligibility."},
      {id:"stud-care",title:"Care and custody",text:"When either dog is in the other party’s custody, the receiving party will provide reasonable safe care and promptly seek emergency veterinary treatment when necessary. Expense and authorization limits are: [CARE TERMS]."},
      {id:"stud-genetics",title:"Genetic and outcome limitations",text:"Each owner has disclosed known material health and genetic information. No guarantee is made regarding litter size, sex, color, coat, show quality, fertility, temperament, or genetic outcome except for a specific written representation in this Agreement."},
      {id:"stud-puppy",title:"Puppy-back option",text:"If compensation includes a puppy, selection order, sex or quality criteria, selection date, transfer expenses, registration, and alternative payment are: [PUPPY-BACK TERMS]."},
      {id:"stud-registration",title:"Litter registration",text:"The parties will cooperate with authorized litter registration after contractual payments and documentation are complete. Stud ownership does not give the stud owner ownership of the litter unless expressly stated."},
      {id:"stud-state",title:"Governing law",text:"This Agreement is governed by {{STATE}} law. Written amendments must be accepted by both owners."}
    ]
  }
];

export const starterClauses = templates[0].clauses;
